# default pre-commit config file
# https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
        exclude: ^.gitlab
      - id: check-yaml
      - id: end-of-file-fixer
