apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-manager
rules:
- apiGroups: ["", "apps", "batch", "networking.k8s.io"]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-manager
subjects:
- kind: ServiceAccount
  name: gitlab
  namespace: "dev"
roleRef:
  kind: ClusterRole
  name: resource-manager
  apiGroup: rbac.authorization.k8s.io